version = 1
exclude_patterns = [
  "bin/**",
  "site/**",
  "doc/**",
  "docs/**",
  "target/**",
  "reports/**"  
]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"
